### ISSUE TITLE
Please create a tag

### ISSUE THREAD

**Issue by SabineMa** [pharo-contributions/OrderPreservingDictionary#1]
This is the same situation as here and  I kindly ask for tagging the current master.

https://github.com/hernanmd/FixedDecimal/issues/1

**Comment by astares** [comment]
Already solved in 2019, more tags will follow ;)

<img width="208" alt="image" src="https://github.com/pharo-contributions/OrderPreservingDictionary/assets/5980033/eb8cde3e-035e-4d68-8db5-59981192fc16">
